# Generated by Django 3.1.7 on 2021-03-10 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_auto_20210310_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckcards',
            name='name',
            field=models.ForeignKey(default='nobody', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
